version: '3.7'
services:
  docker-mariadb:
    hostname: docker-mariadb
    container_name: docker-mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: examplepass
  docker-phpmyadmin:
    hostname: docker-phpmyadmin
    container_name: docker-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8181:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: examplepass
      PMA_HOST: docker-mariadb